In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
%matplotlib inline

In [ ]:
!gdown --id 1MIKKj8Gi-xUwhsYt6xEV6FSmX0_Le8iL
!unzip -q 'data-storm-20.zip'

Downloading...
From: https://drive.google.com/uc?id=1MIKKj8Gi-xUwhsYt6xEV6FSmX0_Le8iL
To: /content/data-storm-20.zip
100% 1.23M/1.23M [00:00<00:00, 79.5MB/s]
replace DataStorm2.0_Q1-v2.pdf? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace Hotel-A-data-dictionary.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: A


In [ ]:
data_train = pd.read_csv('cleaned_training_data.csv')
data_validation = pd.read_csv('Hotel-A-validation.csv', index_col = 0)
columns = data_train.columns.tolist()
drop_list = ['Reservation-id','Expected_checkin', 'Expected_checkout', 'Booking_date']   
data_train = data_train.drop(drop_list, 1)
columns = data_train.columns.tolist().remove('Reservation_Status') 

In [ ]:
from sklearn.utils import shuffle
data_train = shuffle(data_train)

In [ ]:
x = data_train.drop('Reservation_Status', 1)
y = data_train['Reservation_Status']

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = .5)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
train_img = scaler.transform(x_train)
test_img = scaler.transform(x_test)
train_img

array([[ 1.00996769, -0.19931331, -0.28324646, ..., -1.0393618 ,
         0.12970202,  0.96133918],
       [ 1.00996769, -1.05047294, -0.28324646, ..., -0.8309135 ,
         1.32708544,  0.96133918],
       [-0.99013069, -0.33026095, -1.13068851, ...,  0.5500565 ,
         1.32708544,  0.96133918],
       ...,
       [ 1.00996769, -0.98499912, -0.28324646, ..., -0.3488768 ,
        -0.46898969, -1.04021558],
       [ 1.00996769,  1.63395357,  0.56419558, ...,  1.04512121,
        -0.76833554, -1.04021558],
       [ 1.00996769, -0.65763003, -1.13068851, ..., -0.30979275,
        -1.36702725,  0.96133918]])

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(.95)
pca.fit(train_img)
train_img = pca.transform(train_img)
test_img = pca.transform(test_img)

In [ ]:
from sklearn.linear_model import LogisticRegression #trying different models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
#from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

In [ ]:
classifiers = [['Logistic Regression :', LogisticRegression(max_iter = 1500)],
       ['Decision Tree Classification :', DecisionTreeClassifier()],
       ['Gradient Boosting Classification :', GradientBoostingClassifier()],
       ['Ada Boosting Classification :', AdaBoostClassifier()],
       ['RandomForest Classification :', AdaBoostClassifier()],
       ['Extra Tree Classification :', ExtraTreesClassifier()],
       ['K-Neighbors Classification :', KNeighborsClassifier()],
       ['Support Vector Classification :',SVC()],
       ['Gaussian Naive Bayes :',GaussianNB()]]

cla_pred = []
from sklearn.metrics import confusion_matrix, classification_report
for name,model in classifiers:
  model = model
  model.fit(train_img,y_train)
  predictions = model.predict(test_img)
  cla_pred.append(accuracy_score(y_test,predictions))
  print(name,accuracy_score(y_test,predictions))
  print(confusion_matrix(y_test,predictions))
  print(classification_report(y_test,predictions))

Logistic Regression : 0.7527770431102883
[[11385     0     0]
 [ 2448     0     0]
 [ 1291     0     0]]
              precision    recall  f1-score   support

           1       0.75      1.00      0.86     11385
           2       0.00      0.00      0.00      2448
           3       0.00      0.00      0.00      1291

    accuracy                           0.75     15124
   macro avg       0.25      0.33      0.29     15124
weighted avg       0.57      0.75      0.65     15124



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Decision Tree Classification : 0.6094287225601692
[[8609 1818  958]
 [1721  485  242]
 [ 910  258  123]]
              precision    recall  f1-score   support

           1       0.77      0.76      0.76     11385
           2       0.19      0.20      0.19      2448
           3       0.09      0.10      0.09      1291

    accuracy                           0.61     15124
   macro avg       0.35      0.35      0.35     15124
weighted avg       0.62      0.61      0.61     15124

Gradient Boosting Classification : 0.75191748214758
[[11364    14     7]
 [ 2442     6     0]
 [ 1284     5     2]]
              precision    recall  f1-score   support

           1       0.75      1.00      0.86     11385
           2       0.24      0.00      0.00      2448
           3       0.22      0.00      0.00      1291

    accuracy                           0.75     15124
   macro avg       0.41      0.33      0.29     15124
weighted avg       0.62      0.75      0.65     15124

Ada Boosting Clas

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


RandomForest Classification : 0.7523803226659613
[[11378     7     0]
 [ 2447     1     0]
 [ 1291     0     0]]
              precision    recall  f1-score   support

           1       0.75      1.00      0.86     11385
           2       0.12      0.00      0.00      2448
           3       0.00      0.00      0.00      1291

    accuracy                           0.75     15124
   macro avg       0.29      0.33      0.29     15124
weighted avg       0.59      0.75      0.65     15124



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Extra Tree Classification : 0.7526448029621793
[[11379     6     0]
 [ 2444     4     0]
 [ 1287     4     0]]
              precision    recall  f1-score   support

           1       0.75      1.00      0.86     11385
           2       0.29      0.00      0.00      2448
           3       0.00      0.00      0.00      1291

    accuracy                           0.75     15124
   macro avg       0.35      0.33      0.29     15124
weighted avg       0.61      0.75      0.65     15124



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


K-Neighbors Classification : 0.730428458079873
[[10896   428    61]
 [ 2292   141    15]
 [ 1206    75    10]]
              precision    recall  f1-score   support

           1       0.76      0.96      0.85     11385
           2       0.22      0.06      0.09      2448
           3       0.12      0.01      0.01      1291

    accuracy                           0.73     15124
   macro avg       0.36      0.34      0.32     15124
weighted avg       0.62      0.73      0.65     15124

Support Vector Classification : 0.7527770431102883
[[11385     0     0]
 [ 2448     0     0]
 [ 1291     0     0]]
              precision    recall  f1-score   support

           1       0.75      1.00      0.86     11385
           2       0.00      0.00      0.00      2448
           3       0.00      0.00      0.00      1291

    accuracy                           0.75     15124
   macro avg       0.25      0.33      0.29     15124
weighted avg       0.57      0.75      0.65     15124

Gaussian Nai

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
